name: Create Release
on:
  push:
    tags:
      # Push events to matching v*, i.e. v1.0, v20.15.10
      - "v*"

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/setup
        with:
          node-version: 18.x
      - name: Build
        run: npm run build
      - name: Target commitish
        id: target_commitish
        run: |
          echo "value=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Create Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          target_commitish: ${{ steps.target_commitish.outputs.value }}
          generate_release_notes: true
          draft: false
          prerelease: false
