name: "🧪"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: ./.github/setup
        with:
          node-version: 18.x
          install-system-deps: false
      - name: Run Jest tests
        run: npm test
      - name: List coverage files
        run: ls -l coverage
      - name: Upload test coverage
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage
      - uses: ./action.yml
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          delete-old-comments: true
          update-comment: true
